/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;

class AppTest {
    private CustomerAccountRepository mysqlRepository;
    private CustomerAccountRepository postgresRepository;
    private Connection mysqlConnection;
    private Connection postgresConnection;

    // @BeforeEach
    // void setUp() throws SQLException {
    //     // Setup MySQL connection and repository
    //     mysqlConnection = DriverManager.getConnection(
    //             "jdbc:mysql://localhost:3306/customer_db", "alfa", "1234"
    //     );
    //     mysqlRepository = new MySQLCustomerAccountRepository();

    //     // Setup PostgreSQL connection and repository
    //     postgresConnection = DriverManager.getConnection(
    //             "jdbc:postgresql://localhost:5432/customer_db", "postgres", "1234"
    //     );
    //     postgresRepository = new PostgreSQLCustomerAccountRepository();

    //     // Clear the test data before running tests
    //     mysqlConnection.createStatement().execute("DELETE FROM customer_accounts");
    //     postgresConnection.createStatement().execute("DELETE FROM customer_accounts");
    // }

    // @AfterEach
    // void tearDown() throws SQLException {
    //     // Clean up database after test
    //     mysqlConnection.createStatement().execute("DELETE FROM customer_accounts");
    //     postgresConnection.createStatement().execute("DELETE FROM customer_accounts");

    //     mysqlConnection.close();
    //     postgresConnection.close();
    // }

    // @Test
    // void testSaveAndFindById_MySQL() throws SQLException {
    //     CustomerAccount account = new CustomerAccount("C001", "Alice", 500.0);
    //     mysqlRepository.save(account);

    //     CustomerAccount retrieved = mysqlRepository.findById("C001");
    //     assertNotNull(retrieved, "Customer account should be found in MySQL");
    //     assertEquals("Alice", retrieved.getName());
    //     assertEquals(500.0, retrieved.getBalance());
    // }

    // @Test
    // void testSaveAndFindById_PostgreSQL() throws SQLException {
    //     CustomerAccount account = new CustomerAccount("C001", "Alice", 500.0);
    //     postgresRepository.save(account);

    //     CustomerAccount retrieved = postgresRepository.findById("C001");
    //     assertNotNull(retrieved, "Customer account should be found in PostgreSQL");
    //     assertEquals("Alice", retrieved.getName());
    //     assertEquals(500.0, retrieved.getBalance());
    // }
}
